### ISSUE TITLE
Error Code when installing gem.

### ISSUE THREAD

**Issue by LWFlouisa** [reddavis/Naive-Bayes#8]
I keep getting this error code when I install the gem. There is nothing in my data that warrants this error, and was working fine a few days ago.

~~~
/var/lib/gems/3.0.0/gems/naive_bayes-0.0.3/lib/naive_bayes.rb:43:in `block in train': undefined method `[]' for nil:NilClass (NoMethodError)
	from /var/lib/gems/3.0.0/gems/naive_bayes-0.0.3/lib/naive_bayes.rb:42:in `each'
	from /var/lib/gems/3.0.0/gems/naive_bayes-0.0.3/lib/naive_bayes.rb:42:in `train'
	from frequency.rb:160:in `<main>'
~~~

**Comment by LWFlouisa** [comment]
Here we go, resolved it. Apparently it was a misspelling in the labels.
